# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=24
# ============== LAYER base
# or: ARG NODE_VERSION=24.xx.xx
FROM node:${NODE_VERSION}-slim AS base

LABEL fly_launch_runtime="NodeJS"

# NodeJS app lives here
WORKDIR /app/

# Set production environment
ENV NODE_ENV=production


# ============== LAYER installdep
FROM base AS installdep

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install -y curl python-is-python3 pkg-config build-essential 

# Install node modules, thirdparty source and prebuilt dist
WORKDIR /app/
# COPY only copies directory contents, not itself. This is annoying when
# copying multiple file&dirs: https://stackoverflow.com/questions/26504846/copy-directory-to-another-directory-using-add-command/54616645#54616645
COPY --link --parents package.json package-lock.json thirdparty .
# miniflare relies on other packages in workspace, we dont bother pnpm install it, remove it and create a dummy
RUN rm -rfv thirdparty/cloudflare_workers-sdk/packages/miniflare/package && mkdir -vp thirdparty/cloudflare_workers-sdk/packages/miniflare/package
RUN npm install

# RUN ls -la /app/ ; echo ====; ls -la /app/thirdparty/markdowndb/; echo =====; ls -la /app/thirdparty/markdowndb/node_modules/; echo =====; ls -la /app/node_modules/; false

# # Remove development dependencies
# RUN npm prune


# Final stage for app image
# ============== LAYER final
FROM base

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install -y curl busybox python-is-python3 pkg-config build-essential 

RUN ["sh", "-xc", "curl --proto '=https' --tlsv1.2 -LsSf https://github.com/tursodatabase/libsql/releases/download/libsql-server-v0.24.32/libsql-server-installer.sh | sh"]

WORKDIR /app/
# Copy built application
COPY --link --from=installdep /app /app
# COPY --exclude pattern is relative to root already
COPY --link --exclude=thirdparty . .

# RUN ls -la /app/ ; echo ====; ls -la /app/thirdparty/cloudflare_workers-sdk/packages/miniflare/package; echo ====; ls -la /app/thirdparty/markdowndb/; echo =====; ls -la /app/thirdparty/markdowndb/node_modules/; echo =====; ls -la /app/node_modules/; false

# CMD [ "sh", "-c", "npm run esbuildNodeCloudRtServe && npm run nodeCloudServe" ]
CMD [ "sh", "-xc", "echo 'Sorry, docker cmd is not actively used. Please use [processes] in fly.toml . '; sleep 30" ]
