# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=24
# or: ARG NODE_VERSION=24.xx.xx
FROM node:${NODE_VERSION}-slim AS base

LABEL fly_launch_runtime="NodeJS"

# NodeJS app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV=production


# Throw-away build stage to reduce size of final image
FROM base AS build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install -y curl python-is-python3 pkg-config build-essential 

# Install node modules
COPY --link package.json package-lock.json .
RUN npm install

# Copy application code
COPY --link . .

# Remove development dependencies
RUN npm prune


# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app /app

RUN curl --proto '=https' --tlsv1.2 -LsSf https://github.com/tursodatabase/libsql/releases/download/libsql-server-v0.24.32/libsql-server-installer.sh | sh

# Start the server by default, this can be overwritten at runtime
# CMD [ "sh", "-c", "npm run esbuildNodeCloudRtServe && npm run nodeCloudServe" ]
CMD [ "sh", "-xc", "echo 'Sorry, docker cmd is not actively used. Please use [processes] in fly.toml . '; sleep 30" ]
