# fly.toml app configuration file generated for tien-kou on 2026-08-03T18:00:29+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tien-kou'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  PORT = '8571'

[[mounts]]
  source = 'persist_data'
  destination = '/persist'

[processes]
  # two process groups runs in two machines, we dont want that
  # node_cloud_serve = "\"sh\" \"-c\" \"npm run esbuildNodeCloudRtServe && npm run nodeCloudServe\""
  # turso_libsql_server_sqld = "\"sh\" \"-c\" \"/root/.cargo/bin/sqld --db-path /persist/sqld_data.sqld --http-listen-addr 127.0.0.1:7753 --admin-listen-addr 127.0.0.1:7754\""
  # per https://fly.io/docs/app-guides/multiple-processes/#just-use-bash
  mixed = """
/bin/bash -c \"

(
  while true; do
    echo \\\"\\$(date) nodeCloud start\\\" >&2
    npm run esbuildNodeCloudRtServe && npm run nodeCloudServe
    echo \\\"\\$(date) nodeCloud exit \\$? , sleeping 5\\\" >&2
    sleep 5
  done
) &

(
  while true; do
    echo \\\"\\$(date) sqld start\\\" >&2
    echo SQLD_HTTP_AUTH=\\\"\\$(cat /app/.dev.vars | sed -n -E \\\"s/^TURSO_AUTH_TOKEN = \\\\\\\"(.*)\\\\\\\"\\$/\\\\1/p\\\")\\\" >&2
    SQLD_HTTP_AUTH=\\\"\\$(cat /app/.dev.vars | sed -n -E \\\"s/^TURSO_AUTH_TOKEN = \\\\\\\"(.*)\\\\\\\"\\$/\\\\1/p\\\")\\\" /root/.cargo/bin/sqld --db-path /persist/sqld_data.sqld --http-listen-addr 127.0.0.1:7753 --admin-listen-addr 127.0.0.1:7754
    echo \\\"\\$(date) sqld exit \\$? , sleeping 5\\\" >&2
    sleep 5
  done
) &

tail -f /dev/null
\"
"""

[http_service]
  internal_port = 8571
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  # min_machines_running = 0
  min_machines_running = 1
  # processes = ['node_cloud_serve']
  processes = ['mixed']

# The warning "WARNING The app is not listening on the expected address and will not be reachable by fly-proxy." is EXPECTED and there is no good way to get rid of it.
# https://github.com/superfly/flyctl/issues/3358

# [[http_service.checks]]
#   grace_period = "10s"
#   interval = "40s"
#   method = "GET"
#   timeout = "10s"
#   path = "/hello"

[[vm]]
  # 256mb not enough
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[files]]
  guest_path = "/app/.dev.vars"
  # fly secrets set DEV_VARS_FILE=$(cat .dev.vars | base64 | tr -d '\r\n')
  # fly secrets set DEV_VARS_FILE=$(cat .dev.vars.flycloud | base64 | tr -d '\r\n')
  secret_name = "DEV_VARS_FILE"
